#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/


obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8756)	+= touch_ft8756.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8756)	+= touch_ft8756_prd.o
obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8756)	+= touch_ft8756_debug.o
#obj-$(CONFIG_LGE_TOUCH_FOCALTECH_FT8756)	+= fts/

