#
## Makefile for the touchscreen drivers.
#
#
## Each configuration option enables a list of files.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge_sub/

obj-$(CONFIG_LGE_TOUCH_SUB_LGSIC_SW42902)           += sw42902/
obj-$(CONFIG_LGE_TOUCH_SUB_LGSIC_SW42000)           += sw42000/
