# Makefile for the Himax touchscreen drivers.

# Touch Core Driver Common Header Code..!!
ccflags-y += -I$(srctree)/drivers/input/touchscreen/lge/

obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83113A)   	+= touch_hx83113a.o
obj-$(CONFIG_LGE_TOUCH_HIMAX_HX83113A)   	+= touch_hx83113a_prd.o
